<?$APPLICATION->IncludeComponent(
	"dresscode:search.line",
	"version2",
	Array(
		"CACHE_TIME" => "3600000",
		"CACHE_TYPE" => "A",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"HIDE_MEASURES" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "12",
		"IBLOCK_TYPE" => "catalog",
		"PRICE_CODE" => array("BASE"),
		"PROPERTY_CODE" => array("CML2_ARTICLE","OFFERS","ATT_BRAND","COLLECTION","TOTAL_OUTPUT_POWER","VID_ZASTECHKI","VID_SUMKI","VIDEO","VYSOTA_RUCHEK","WARRANTY","OTSEKOV","CONVECTION","NAZNAZHENIE","BULK","PODKLADKA","SEASON","REF","COUNTRY_BRAND","SKU_COLOR","DELIVERY","PICKUP","USER_ID","BLOG_POST_ID","BLOG_COMMENTS_CNT","VOTE_COUNT","SHOW_MENU","SIMILAR_PRODUCT","RATING","RELATED_PRODUCT","VOTE_SUM","COLOR","ZOOM2","BATTERY_LIFE","SWITCH","GRAF_PROC","LENGTH_OF_CORD","DISPLAY","LOADING_LAUNDRY","FULL_HD_VIDEO_RECORD","INTERFACE","COMPRESSORS","Number_of_Outlets","MAX_RESOLUTION_VIDEO","MAX_BUS_FREQUENCY","MAX_RESOLUTION","FREEZER","POWER_SUB","POWER","HARD_DRIVE_SPACE","MEMORY","OS","ZOOM","PAPER_FEED","SUPPORTED_STANDARTS","VIDEO_FORMAT","SUPPORT_2SIM","MP3","ETHERNET_PORTS","MATRIX","CAMERA","PHOTOSENSITIVITY","DEFROST","SPEED_WIFI","SPIN_SPEED","PRINT_SPEED","SOCKET","IMAGE_STABILIZER","GSM","SIM","TYPE","MEMORY_CARD","TYPE_BODY","TYPE_MOUSE","TYPE_PRINT","CONNECTION","TYPE_OF_CONTROL","TYPE_DISPLAY","TYPE2","REFRESH_RATE","RANGE","AMOUNT_MEMORY","MEMORY_CAPACITY","VIDEO_BRAND","DIAGONAL","RESOLUTION","TOUCH","CORES","LINE_PROC","PROCESSOR","CLOCK_SPEED","TYPE_PROCESSOR","PROCESSOR_SPEED","HARD_DRIVE","HARD_DRIVE_TYPE","Number_of_memory_slots","MAXIMUM_MEMORY_FREQUENCY","TYPE_MEMORY","BLUETOOTH","FM","GPS","HDMI","SMART_TV","USB","WIFI","FLASH","ROTARY_DISPLAY","SUPPORT_3D","SUPPORT_3G","WITH_COOLER","FINGERPRINT","PROFILE","GAS_CONTROL","GRILL","MORE_PROPERTIES","GENRE","INTAKE_POWER","SURFACE_COATING","brand_tyres","SEASONOST","DUST_COLLECTION","DRYING","REMOVABLE_TOP_COVER","CONTROL","FINE_FILTER","FORM_FAKTOR","")
	)
);?>